### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by antoniojosesanchez** [PabloMartinTrujillo/OM-Ilustraciones#1]
Incorpora el esquema E/R definitivo. ¿Dos bases de datos? ¿No hay ninguna relación entre el USUARIO y las GALERÍAS?

**Comment by PabloMartinTrujillo** [comment]
No, no se donde hay dos bases de datos. 

Los usuarios no se relacionan con la galería. La galería es para que el administrador incluya imágenes en un tipo de galería. Por ejemplo, una galería de "Línea simple" donde el administrador incluye imágenes de este estilo para mostrarla a los usuarios. Por lo que no tiene sentido relacionar el usuario y las galerías.

El esquema E/R que he actualizado es el definitivo, pero siempre pueden haber cambios y alguna ampliación. Es algo normal y lógico, no puedo tener todo claro desde un primer momento.
